"""rename address

Revision ID: ad6e69ba768b
Revises: 6cf3663441a6
Create Date: 2024-08-13 09:00:48.869316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6e69ba768b'
down_revision = '6cf3663441a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name = 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name = 'address' )
    # ### end Alembic commands ###

